#ifndef __UI_CLASS_ID_H__
#define __UI_CLASS_ID_H__

#define UI_CLASS_ID_BASE 0x1000

#define UI_DEFAULT_CONTROL_CLASS_ID ( UI_CLASS_ID_BASE + 0 )

#define UI_CONTROL_CLASS_NAME _T("ControlUI")
#define UI_CONTROL_INTERFACE_NAME _T("Control")
#define UI_CONTROL_CLASS_ID ( UI_CLASS_ID_BASE + 1 )

#define UI_ACTIVEX_CLASS_NAME _T("ActiveXUI")
#define UI_ACTIVEX_INTERFACE_NAME _T("ActiveX")
#define UI_ACTIVEX_CLASS_ID ( UI_CLASS_ID_BASE + 2 )

#define UI_COMBO_CLASS_NAME _T("ComboUI")
#define UI_COMBO_INTERFACE_NAME _T("Combo")
#define UI_COMBO_CLASS_ID ( UI_CLASS_ID_BASE + 3 )

#define UI_LIST_CLASS_NAME _T("ListUI")
#define UI_LIST_INTERFACE_NAME _T("List")
#define UI_LIST_INTERFACE_EX_NAME _T("IList")
#define UI_LIST_OWNER_INTERFACE_NAME _T("IListOwner")

#define UI_LIST_CLASS_ID ( UI_CLASS_ID_BASE + 4 )

#define UI_LIST_HEADER_CLASS_NAME _T("ListHeaderUI")
#define UI_LIST_HEADER_INTERFACE_NAME _T("ListHeader")
#define UI_LIST_HEADER_CLASS_ID ( UI_CLASS_ID_BASE + 5 )

#define UI_LIST_HEADER_ITEM_CLASS_NAME _T("ListHeaderItemUI")
#define UI_LIST_HEADER_ITEM_INTERFACE_NAME _T("")
#define UI_LIST_HEADER_ITEM_CLASS_ID ( UI_CLASS_ID_BASE + 6 )

#define UI_LIST_ELEMENT_CLASS_NAME _T("ListElementUI")
#define UI_LIST_ELEMENT_INTERFACE_NAME _T("ListElement")
#define UI_LIST_ITEM_INTERFACE_NAME _T("ListItem")
#define UI_LIST_ELEMENT_CLASS_ID ( UI_CLASS_ID_BASE + 7 )

#define UI_LIST_LABEL_ELEMENT_CLASS_NAME _T("ListLabelElementUI")
#define UI_LIST_LABEL_ELEMENT_INTERFACE_NAME _T("ListLabelElement")
#define UI_LIST_LABEL_ELEMENT_CLASS_ID ( UI_CLASS_ID_BASE + 8 )

#define UI_LIST_TEXT_ELEMENT_CLASS_NAME _T("ListTextElementUI")
#define UI_LIST_TEXT_ELEMENT_INTERFACE_NAME _T("ListTextElement")
#define UI_LIST_TEXT_ELEMENT_CLASS_ID ( UI_CLASS_ID_BASE + 9 )

#define UI_LIST_CONTAINER_ELEMENT_CLASS_NAME _T("ListContainerElementUI")
#define UI_LIST_CONTAINER_ELEMENT_INTERFACE_NAME _T("ListContainerElement")
#define UI_LIST_CONTAINER_ELEMENT_CLASS_ID ( UI_CLASS_ID_BASE + 10 )

#define IS_UI_LIST_ELEMENT_CLASS_ID( _class_id_ ) ( ( _class_id_ ) >= UI_LIST_ELEMENT_CLASS_ID && ( _class_id_ <= UI_LIST_CONTAINER_ELEMENT_CLASS_ID ) ) 

#define UI_LABEL_CLASS_NAME _T("LabelUI")
#define UI_LABEL_INTERFACE_NAME _T("Label")
#define UI_LABEL_CLASS_ID ( UI_CLASS_ID_BASE + 11 )

#define UI_BUTTON_CLASS_NAME _T("ButtonUI")
#define UI_BUTTON_INTERFACE_NAME _T("Button")
#define UI_BUTTON_CLASS_ID ( UI_CLASS_ID_BASE + 12 )

#define UI_BUTTON_EX_CLASS_NAME _T("ButtonExUI")
#define UI_BUTTON_EX_INTERFACE_NAME _T("ButtonEx")
#define UI_BUTTON_EX_CLASS_ID ( UI_CLASS_ID_BASE + 13 )

#define UI_OPTION_CLASS_NAME _T("OptionUI")
#define UI_OPTION_INTERFACE_NAME _T("Option")
#define UI_OPTION_CLASS_ID ( UI_CLASS_ID_BASE + 14 )

#define UI_TEXT_CLASS_NAME _T("TextUI")
#define UI_TEXT_INTERFACE_NAME _T("Text")
#define UI_TEXT_CLASS_ID ( UI_CLASS_ID_BASE + 15 )

#define UI_PROGRESS_CLASS_NAME _T("ProgressUI")
#define UI_PROGRESS_INTERFACE_NAME _T("Progress")
#define UI_PROGRESS_CLASS_ID ( UI_CLASS_ID_BASE + 16 )

#define UI_SLIDER_CLASS_NAME _T("SliderUI")
#define UI_SLIDER_INTERFACE_NAME _T("Slider")
#define UI_SLIDER_CLASS_ID ( UI_CLASS_ID_BASE + 17 )

#define UI_EDIT_CLASS_NAME _T("EditUI")
#define UI_EDIT_INTERFACE_NAME _T("Edit")
#define UI_EDIT_CLASS_ID ( UI_CLASS_ID_BASE + 18 )

#define UI_SCROLL_BAR_CLASS_NAME _T("ScrollBarUI")
#define UI_SCROLL_BAR_INTERFACE_NAME _T("ScrollBar")
#define UI_SCROLL_BAR_CLASS_ID ( UI_CLASS_ID_BASE + 19 )

#define UI_CONTAINER_CLASS_NAME _T("ContainerUI")
#define UI_CONTAINER_INTERFACE_NAME _T("Container")
#define UI_CONTAINER_CLASS_ID ( UI_CLASS_ID_BASE + 20 )

#define UI_VERTICAL_LAYOUT_CLASS_NAME _T("VerticalLayoutUI")
#define UI_VERTICAL_LAYOUT_INTERFACE_NAME _T("VerticalLayout")
#define UI_VERTICAL_LAYOUT_CLASS_ID ( UI_CLASS_ID_BASE + 21 )

#define UI_HORIZONTAL_LAYOUT_CLASS_NAME _T("HorizontalLayoutUI")
#define UI_HORIZONTAL_LAYOUT_INTERFACE_NAME _T("HorizontalLayout")
#define UI_HORIZONTAL_LAYOUT_CLASS_ID ( UI_CLASS_ID_BASE + 22 )

#define UI_TILE_LAYOUT_CLASS_NAME _T("TileLayoutUI")
#define UI_TILE_LAYOUT_INTERFACE_NAME _T("TileLayout")
#define UI_TILE_LAYOUT_CLASS_ID ( UI_CLASS_ID_BASE + 23 )

#define UI_TAB_LAYOUT_CLASS_NAME _T("TabLayoutUI")
#define UI_TAB_LAYOUT_INTERFACE_NAME _T("TabLayout")
#define UI_TAB_LAYOUT_CLASS_ID ( UI_CLASS_ID_BASE + 24 )

#define UI_DIALOG_LAYOUT_CLASS_NAME _T("DialogLayoutUI")
#define UI_DIALOG_LAYOUT_INTERFACE_NAME _T("DialogLayout")
#define UI_DIALOG_LAYOUT_CLASS_ID ( UI_CLASS_ID_BASE + 25 )

#define UI_RICH_EDIT_CLASS_NAME _T("RichEditUI")
#define UI_RICH_EDIT_INTERFACE_NAME _T("RichEdit")
#define UI_RICH_EDIT_CLASS_ID ( UI_CLASS_ID_BASE + 26 )

#define UI_LIST_EX_CLASS_NAME _T("ListExUI")
#define UI_LIST_EX_INTERFACE_NAME _T("IListExUI")
#define UI_LIST_EX_CLASS_ID ( UI_CLASS_ID_BASE + 27 )

#define UI_LIST_BODY_EX_CLASS_NAME _T("ListBodyExUI" )
//#define UI_LIST_BODY_EX_INTERFACE_NAME _T("")
#define UI_LIST_BODY_EX_CLASS_ID ( UI_CLASS_ID_BASE + 28 )

#define UI_LIST_CONTAINER_ELEMENT_EX_CLASS_NAME _T("ListContainerElementExUI")
#define UI_LIST_CONTAINER_ELEMENT_EX_CLASS_ID ( UI_CLASS_ID_BASE + 29 )

#define UI_EVENT_LIST_ELEMENT_CLASS_NAME _T("EventListItemUI")
#define UI_EVENT_LIST_ELEMENT_CLASS_ID ( UI_CLASS_ID_BASE + 30 )

//#define UI__CLASS_NAME _T("")
//#define UI__INTERFACE_NAME _T("")
//#define UI__CLASS_ID ( UI_CLASS_ID_BASE + 28 )

//#define UI__CLASS_NAME _T("")
//#define UI__INTERFACE_NAME _T("")
//#define UI__CLASS_ID ( UI_CLASS_ID_BASE + 28 )

#define UI_SCROLL_BAR_CLASS_NAME _T("ScrollBarUI")

#endif //__UI_CLASS_ID_H__
